--what is the total revenue generated by male vs female customer?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from customer)

--which are the top 5 productswith the highest average review rating?
select item_purchased, Round (AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;